export const defaultGames = [
  {
    id: "cyberpunk",
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.8,
    releaseDate: "2020-12-10",
    description: "An open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Upgraded with next-gen graphics and fully immersive ray-tracing options.",
    playtime: 151200,
    lastPlayed: "Yesterday",
    progress: 73,
    timeToComplete: "12 hrs",
    nextAchievement: "The Star (80% complete)",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: true,
    owned: true,
    tags: ["Open World", "Sci-Fi", "Ray Tracing"],
    steamAppId: "1091500",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "eldenring",
    title: "Elden Ring",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2022-02-25",
    description: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between. Experience an expansive fantasy landscape of breathtaking scale.",
    playtime: 414000,
    lastPlayed: "2 days ago",
    progress: 92,
    timeToComplete: "8 hrs",
    nextAchievement: "Elden Lord (90% complete)",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: true,
    owned: true,
    tags: ["Souls-like", "Dark Fantasy", "Hardcore"],
    steamAppId: "1245620",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "hades",
    title: "Hades",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genre: "Rogue-like",
    rating: 4.8,
    releaseDate: "2020-09-17",
    description: "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.",
    playtime: 126000,
    lastPlayed: "5 days ago",
    progress: 64,
    timeToComplete: "5 hrs",
    nextAchievement: "Family Reunion (50% complete)",
    coverUrl: null,
    bannerUrl: null,
    soundType: "guitar",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: false,
    owned: true,
    tags: ["Hack & Slash", "Indie", "Rogue-like"],
    steamAppId: "1145360",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "portal2",
    title: "Portal 2",
    developer: "Valve",
    publisher: "Valve",
    genre: "Puzzle Platformer",
    rating: 4.9,
    releaseDate: "2011-04-18",
    description: "The cooperative mode of Portal 2 features a unique two-player campaign with its own story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew.",
    playtime: 90000,
    lastPlayed: "3 weeks ago",
    progress: 100,
    timeToComplete: "0 hrs",
    nextAchievement: "Completed (100% complete)",
    coverUrl: null,
    bannerUrl: null,
    soundType: "ambient",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: false,
    owned: true,
    tags: ["Puzzle", "Co-op", "Comedy"],
    steamAppId: "620",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "witcher3",
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2015-05-19",
    description: "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy.",
    playtime: 216000,
    lastPlayed: "1 month ago",
    progress: 45,
    timeToComplete: "40 hrs",
    nextAchievement: "Gwent Master (30% complete)",
    coverUrl: null,
    bannerUrl: null,
    soundType: "folkish",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: false,
    owned: true,
    tags: ["Rich Story", "Fantasy", "Open World"],
    steamAppId: "292030",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  }
];

const libraryCatalog = {
  "cyberpunk2077": {
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    genre: "Action RPG",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    tags: ["Open World", "Sci-Fi", "Ray Tracing"],
    steamAppId: "1091500"
  },
  "eldenring": {
    title: "Elden Ring",
    developer: "FromSoftware",
    genre: "Action RPG",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["Souls-like", "Dark Fantasy", "Hardcore"],
    steamAppId: "1245620"
  },
  "hades": {
    title: "Hades",
    developer: "Supergiant Games",
    genre: "Rogue-like",
    coverUrl: null,
    bannerUrl: null,
    soundType: "guitar",
    tags: ["Hack & Slash", "Indie", "Rogue-like"],
    steamAppId: "1145360"
  },
  "portal2": {
    title: "Portal 2",
    developer: "Valve",
    genre: "Puzzle Platformer",
    coverUrl: null,
    bannerUrl: null,
    soundType: "ambient",
    tags: ["Puzzle", "Co-op", "Comedy"],
    steamAppId: "620"
  },
  "witcher3": {
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    genre: "Action RPG",
    coverUrl: null,
    bannerUrl: null,
    soundType: "folkish",
    tags: ["Rich Story", "Fantasy", "Open World"],
    steamAppId: "292030"
  },
  "minecraft": {
    title: "Minecraft",
    developer: "Mojang",
    genre: "Sandbox",
    coverUrl: null,
    bannerUrl: null,
    soundType: "ambient",
    tags: ["Survival", "Building", "Sandbox"],
    steamAppId: null
  }
};

export function matchGameMetadata(exeName, fullPath) {
  const sanitized = exeName.toLowerCase().replace(/[^a-z0-9]/g, "");

  for (const [key, meta] of Object.entries(libraryCatalog)) {
    if (sanitized.includes(key) || key.includes(sanitized)) {
      return {
        ...meta,
        exePath: fullPath,
        playtime: 0,
        lastPlayed: "Never",
        progress: 0,
        timeToComplete: "--",
        nextAchievement: "Locked (0% complete)",
        rating: 4.5,
        releaseDate: new Date().toISOString().split('T')[0],
        description: `Your scanned copy of ${meta.title}. Imported automatically by Nexus Launcher. Run the game to begin tracking playtime.`,
        isFavorite: false,
        logoUrl: null,
        iconUrl: null,
        artworkFetched: false
      };
    }
  }

  const randomId = Math.floor(Math.random() * 1000) + 100;
  return {
    title: exeName.charAt(0).toUpperCase() + exeName.slice(1).replace(/[-_]/g, ' '),
    developer: "Unknown Developer",
    genre: "Indie Game",
    rating: 4.0,
    releaseDate: new Date().toISOString().split('T')[0],
    description: `A local executable found at ${fullPath}. Fully compatible with Nexus runtime launcher and session playtime counters. Customise this game card using the Metadata Suite.`,
    playtime: 0,
    lastPlayed: "Never",
    progress: 0,
    timeToComplete: "--",
    nextAchievement: "None",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    exePath: fullPath,
    isFavorite: false,
    owned: true,
    tags: ["Local Import"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  };
}

export const storeCatalog = [
  {
    id: "cyberpunk",
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.8,
    releaseDate: "2020-12-10",
    description: "An open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Upgraded with next-gen graphics and fully immersive ray-tracing options.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    tags: ["Open World", "Sci-Fi", "Ray Tracing"],
    owned: false,
    steamAppId: "1091500",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "eldenring",
    title: "Elden Ring",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2022-02-25",
    description: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between. Experience an expansive fantasy landscape of breathtaking scale.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["Souls-like", "Dark Fantasy", "Hardcore"],
    owned: false,
    steamAppId: "1245620",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "hades",
    title: "Hades",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genre: "Rogue-like",
    rating: 4.8,
    releaseDate: "2020-09-17",
    description: "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "guitar",
    tags: ["Hack & Slash", "Indie", "Rogue-like"],
    owned: false,
    steamAppId: "1145360",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "portal2",
    title: "Portal 2",
    developer: "Valve",
    publisher: "Valve",
    genre: "Puzzle Platformer",
    rating: 4.9,
    releaseDate: "2011-04-18",
    description: "The cooperative mode of Portal 2 features a unique two-player campaign with its own story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "ambient",
    tags: ["Puzzle", "Co-op", "Comedy"],
    owned: false,
    steamAppId: "620",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "witcher3",
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2015-05-19",
    description: "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "folkish",
    tags: ["Rich Story", "Fantasy", "Open World"],
    owned: false,
    steamAppId: "292030",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "godofwar",
    title: "God of War Ragnarök",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    genre: "Action Adventure",
    rating: 4.9,
    releaseDate: "2022-11-09",
    description: "Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go. The breathtakingly cinematic action-adventure saga continues as the end of days approaches.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["Story Rich", "Mythology", "Action"],
    owned: false,
    steamAppId: "2322010",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "spiderman",
    title: "Marvel's Spider-Man 2",
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    genre: "Action Adventure",
    rating: 4.8,
    releaseDate: "2023-10-20",
    description: "Swing, fight, and soar across Marvel's New York as both Peter Parker and Miles Morales. Battle iconic villains and protect the city in this thrilling sequel.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    tags: ["Superhero", "Open World", "Action"],
    owned: false,
    steamAppId: "2651280",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "minecraft",
    title: "Minecraft",
    developer: "Mojang",
    publisher: "Mojang",
    genre: "Sandbox",
    rating: 4.7,
    releaseDate: "2011-11-18",
    description: "Explore infinite worlds and build everything from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "ambient",
    tags: ["Survival", "Building", "Sandbox"],
    owned: false,
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "baldursgate3",
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genre: "CRPG",
    rating: 4.9,
    releaseDate: "2023-08-03",
    description: "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power. Master deep strategic combat and rich storytelling.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["RPG", "Strategy", "Story Rich"],
    owned: false,
    steamAppId: "1086940",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "zelda",
    title: "The Legend of Zelda: Tears of the Kingdom",
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: "Action Adventure",
    rating: 5.0,
    releaseDate: "2023-05-12",
    description: "An epic adventure across the land and skies of Hyrule awaits in this long-awaited sequel to Breath of the Wild. Harness the power of new abilities and explore a vast, reimagined world.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["Adventure", "Open World", "Puzzle"],
    owned: false,
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "halo",
    title: "Halo Infinite",
    developer: "343 Industries",
    publisher: "Xbox Game Studios",
    genre: "First-Person Shooter",
    rating: 4.5,
    releaseDate: "2021-12-08",
    description: "When all hope is lost and humanity's fate hangs in the balance, the Master Chief steps forward to confront a terrifying new enemy. The most ambitious Halo campaign ever made.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    tags: ["Sci-Fi", "Shooter", "Multiplayer"],
    owned: false,
    steamAppId: "1240440",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "ff7rebirth",
    title: "Final Fantasy VII Rebirth",
    developer: "Square Enix",
    publisher: "Square Enix",
    genre: "JRPG",
    rating: 4.8,
    releaseDate: "2024-02-29",
    description: "Step into a vibrant and vast world as Cloud and his friends seek to defy destiny itself. The second chapter of the FINAL FANTASY VII remake project blends classic RPG storytelling with action combat.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["RPG", "Fantasy", "Action"],
    owned: false,
    steamAppId: "2909400",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "starfield",
    title: "Starfield",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    genre: "Action RPG",
    rating: 4.3,
    releaseDate: "2023-09-06",
    description: "Explore the vast reaches of space in Bethesda's first new universe in over 25 years. Create your character and embark on an epic journey to uncover humanity's greatest mystery.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    tags: ["Space", "Open World", "Sci-Fi"],
    owned: false,
    steamAppId: "1716740",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "horizon",
    title: "Horizon Forbidden West",
    developer: "Guerrilla Games",
    publisher: "Sony Interactive Entertainment",
    genre: "Action RPG",
    rating: 4.7,
    releaseDate: "2022-02-18",
    description: "Aloy ventures west to investigate a deadly blight that threatens all life on Earth. Explore stunning landscapes, battle colossal machines, and uncover a hidden threat.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["Open World", "Sci-Fi", "Action"],
    owned: false,
    steamAppId: "2420110",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "diablo4",
    title: "Diablo IV",
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    genre: "Action RPG",
    rating: 4.4,
    releaseDate: "2023-06-06",
    description: "Explore the shattered world of Sanctuary in the most ambitious Diablo entry yet. Battle the legions of Hell through a dark and gripping campaign, then dive into deep endgame content.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "ambient",
    tags: ["Dark Fantasy", "Multiplayer", "RPG"],
    owned: false,
    steamAppId: "2344520",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "starwars",
    title: "Star Wars Jedi: Survivor",
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    genre: "Action Adventure",
    rating: 4.6,
    releaseDate: "2023-04-28",
    description: "Continue Cal Kestis's journey across the galaxy, now a more powerful Jedi. Master new combat abilities and explore a galaxy far, far away in this thrilling action-adventure.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["Sci-Fi", "Action", "Adventure"],
    owned: false,
    steamAppId: "1774580",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "liesofp",
    title: "Lies of P",
    developer: "Neowiz Games",
    publisher: "Neowiz",
    genre: "Souls-like",
    rating: 4.6,
    releaseDate: "2023-09-19",
    description: "A dark fantasy retelling of Pinocchio. Navigate a ruined city in a desperate search for Geppetto. Master a sophisticated combat system and wield a unique weapon customization system.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "orchestra",
    tags: ["Souls-like", "Dark Fantasy", "Action"],
    owned: false,
    steamAppId: "1627720",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "cyberpunk2077phantom",
    title: "Cyberpunk 2077: Phantom Liberty",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2023-09-26",
    description: "A spy-thriller expansion for Cyberpunk 2077. When a prototype orbital shuttle crash-lands in Dogtown, V is pulled into a dangerous game of espionage and survival featuring Idris Elba.",
    coverUrl: null,
    bannerUrl: null,
    soundType: "synth",
    tags: ["Open World", "Spy Thriller", "Expansion"],
    owned: false,
    steamAppId: "2138330",
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  }
];
