export const defaultGames = [
  {
    id: "cyberpunk",
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.8,
    releaseDate: "2020-12-10",
    description: "An open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Upgraded with next-gen graphics and fully immersive ray-tracing options.",
    playtime: 151200,
    lastPlayed: "Yesterday",
    progress: 73,
    timeToComplete: "12 hrs",
    nextAchievement: "The Star (80% complete)",
    coverUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&q=80",
    soundType: "synth",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: true,
    owned: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    tags: ["Open World", "Sci-Fi", "Ray Tracing"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "eldenring",
    title: "Elden Ring",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2022-02-25",
    description: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between. Experience an expansive fantasy landscape of breathtaking scale.",
    playtime: 414000,
    lastPlayed: "2 days ago",
    progress: 92,
    timeToComplete: "8 hrs",
    nextAchievement: "Elden Lord (90% complete)",
    coverUrl: "https://images.unsplash.com/photo-1655821888788-6107699e173b?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&q=80",
    soundType: "orchestra",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: true,
    owned: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    tags: ["Souls-like", "Dark Fantasy", "Hardcore"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "hades",
    title: "Hades",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genre: "Rogue-like",
    rating: 4.8,
    releaseDate: "2020-09-17",
    description: "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.",
    playtime: 126000,
    lastPlayed: "5 days ago",
    progress: 64,
    timeToComplete: "5 hrs",
    nextAchievement: "Family Reunion (50% complete)",
    coverUrl: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=80",
    soundType: "guitar",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: false,
    owned: true,
    platforms: ["PC", "PS5", "Xbox Series X|S", "Switch"],
    tags: ["Hack & Slash", "Indie", "Rogue-like"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "portal2",
    title: "Portal 2",
    developer: "Valve",
    publisher: "Valve",
    genre: "Puzzle Platformer",
    rating: 4.9,
    releaseDate: "2011-04-18",
    description: "The cooperative mode of Portal 2 features a unique two-player campaign with its own story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew.",
    playtime: 90000,
    lastPlayed: "3 weeks ago",
    progress: 100,
    timeToComplete: "0 hrs",
    nextAchievement: "Completed (100% complete)",
    coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600&q=80",
    soundType: "ambient",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: false,
    owned: true,
    platforms: ["PC", "PS5", "Xbox Series X|S", "Switch"],
    tags: ["Puzzle", "Co-op", "Comedy"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "witcher3",
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2015-05-19",
    description: "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy.",
    playtime: 216000,
    lastPlayed: "1 month ago",
    progress: 45,
    timeToComplete: "40 hrs",
    nextAchievement: "Gwent Master (30% complete)",
    coverUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&q=80",
    soundType: "folkish",
    exePath: "C:\\Windows\\notepad.exe",
    isFavorite: false,
    owned: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    tags: ["Rich Story", "Fantasy", "Open World"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  }
];

const libraryCatalog = {
  "cyberpunk2077": {
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    genre: "Action RPG",
    coverUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&q=80",
    soundType: "synth",
    tags: ["Open World", "Sci-Fi", "Ray Tracing"],
    steamAppId: null
  },
  "eldenring": {
    title: "Elden Ring",
    developer: "FromSoftware",
    genre: "Action RPG",
    coverUrl: "https://images.unsplash.com/photo-1655821888788-6107699e173b?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&q=80",
    soundType: "orchestra",
    tags: ["Souls-like", "Dark Fantasy", "Hardcore"],
    steamAppId: null
  },
  "hades": {
    title: "Hades",
    developer: "Supergiant Games",
    genre: "Rogue-like",
    coverUrl: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=80",
    soundType: "guitar",
    tags: ["Hack & Slash", "Indie", "Rogue-like"],
    steamAppId: null
  },
  "portal2": {
    title: "Portal 2",
    developer: "Valve",
    genre: "Puzzle Platformer",
    coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600&q=80",
    soundType: "ambient",
    tags: ["Puzzle", "Co-op", "Comedy"],
    steamAppId: null
  },
  "witcher3": {
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    genre: "Action RPG",
    coverUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&q=80",
    soundType: "folkish",
    tags: ["Rich Story", "Fantasy", "Open World"],
    steamAppId: null
  },
  "minecraft": {
    title: "Minecraft",
    developer: "Mojang",
    genre: "Sandbox",
    coverUrl: "https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1607988795691-3d0147b43231?w=1600&q=80",
    soundType: "ambient",
    tags: ["Survival", "Building", "Sandbox"],
    steamAppId: null
  }
};

export function matchGameMetadata(exeName, fullPath) {
  const sanitized = exeName.toLowerCase().replace(/[^a-z0-9]/g, "");

  for (const [key, meta] of Object.entries(libraryCatalog)) {
    if (sanitized.includes(key) || key.includes(sanitized)) {
      return {
        ...meta,
        exePath: fullPath,
        playtime: 0,
        lastPlayed: "Never",
        progress: 0,
        timeToComplete: "--",
        nextAchievement: "Locked (0% complete)",
        rating: 4.5,
        releaseDate: new Date().toISOString().split('T')[0],
        description: `Your scanned copy of ${meta.title}. Imported automatically by Nexus PS5 Launcher. Run the game to begin tracking playtime.`,
        isFavorite: false,
        logoUrl: null,
        iconUrl: null,
        artworkFetched: false
      };
    }
  }

  const randomId = Math.floor(Math.random() * 1000) + 100;
  return {
    title: exeName.charAt(0).toUpperCase() + exeName.slice(1).replace(/[-_]/g, ' '),
    developer: "Unknown Developer",
    genre: "Indie Game",
    rating: 4.0,
    releaseDate: new Date().toISOString().split('T')[0],
    description: `A local executable found at ${fullPath}. Fully compatible with Nexus runtime launcher and session playtime counters. Customise this game card using the Metadata Suite.`,
    playtime: 0,
    lastPlayed: "Never",
    progress: 0,
    timeToComplete: "--",
    nextAchievement: "None",
    coverUrl: `https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&q=80`,
    bannerUrl: `https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1600&q=80`,
    soundType: "synth",
    exePath: fullPath,
    isFavorite: false,
    owned: true,
    platforms: ["PC"],
    tags: ["Local Import"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  };
}

export const storeCatalog = [
  {
    id: "cyberpunk",
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.8,
    releaseDate: "2020-12-10",
    description: "An open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Upgraded with next-gen graphics and fully immersive ray-tracing options.",
    coverUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&q=80",
    soundType: "synth",
    tags: ["Open World", "Sci-Fi", "Ray Tracing"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "eldenring",
    title: "Elden Ring",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2022-02-25",
    description: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between. Experience an expansive fantasy landscape of breathtaking scale.",
    coverUrl: "https://images.unsplash.com/photo-1655821888788-6107699e173b?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&q=80",
    soundType: "orchestra",
    tags: ["Souls-like", "Dark Fantasy", "Hardcore"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "hades",
    title: "Hades",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genre: "Rogue-like",
    rating: 4.8,
    releaseDate: "2020-09-17",
    description: "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.",
    coverUrl: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=80",
    soundType: "guitar",
    tags: ["Hack & Slash", "Indie", "Rogue-like"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S", "Switch"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "portal2",
    title: "Portal 2",
    developer: "Valve",
    publisher: "Valve",
    genre: "Puzzle Platformer",
    rating: 4.9,
    releaseDate: "2011-04-18",
    description: "The cooperative mode of Portal 2 features a unique two-player campaign with its own story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew.",
    coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600&q=80",
    soundType: "ambient",
    tags: ["Puzzle", "Co-op", "Comedy"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S", "Switch"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "witcher3",
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2015-05-19",
    description: "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy.",
    coverUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&q=80",
    soundType: "folkish",
    tags: ["Rich Story", "Fantasy", "Open World"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "godofwar",
    title: "God of War Ragnarök",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    genre: "Action Adventure",
    rating: 4.9,
    releaseDate: "2022-11-09",
    description: "Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go. The breathtakingly cinematic action-adventure saga continues as the end of days approaches.",
    coverUrl: "https://images.unsplash.com/photo-1608889825205-e3f5e4a2020e?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=80",
    soundType: "orchestra",
    tags: ["Story Rich", "Mythology", "Action"],
    owned: false,
    platforms: ["PS4", "PS5", "PC"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "spiderman",
    title: "Marvel's Spider-Man 2",
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    genre: "Action Adventure",
    rating: 4.8,
    releaseDate: "2023-10-20",
    description: "Swing, fight, and soar across Marvel's New York as both Peter Parker and Miles Morales. Battle iconic villains and protect the city in this thrilling sequel.",
    coverUrl: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1600&q=80",
    soundType: "synth",
    tags: ["Superhero", "Open World", "Action"],
    owned: false,
    platforms: ["PS5"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "minecraft",
    title: "Minecraft",
    developer: "Mojang",
    publisher: "Mojang",
    genre: "Sandbox",
    rating: 4.7,
    releaseDate: "2011-11-18",
    description: "Explore infinite worlds and build everything from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode.",
    coverUrl: "https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1607988795691-3d0147b43231?w=1600&q=80",
    soundType: "ambient",
    tags: ["Survival", "Building", "Sandbox"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S", "Switch", "Mobile"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "baldursgate3",
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genre: "CRPG",
    rating: 4.9,
    releaseDate: "2023-08-03",
    description: "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power. Master deep strategic combat and rich storytelling.",
    coverUrl: "https://images.unsplash.com/photo-1531326121958-9a5a53c8a2c6?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1600&q=80",
    soundType: "orchestra",
    tags: ["RPG", "Strategy", "Story Rich"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "zelda",
    title: "The Legend of Zelda: Tears of the Kingdom",
    developer: "Nintendo EPD",
    publisher: "Nintendo",
    genre: "Action Adventure",
    rating: 5.0,
    releaseDate: "2023-05-12",
    description: "An epic adventure across the land and skies of Hyrule awaits in this long-awaited sequel to Breath of the Wild. Harness the power of new abilities and explore a vast, reimagined world.",
    coverUrl: "https://images.unsplash.com/photo-1616514197671-15d99ce7a6f8?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1470071459604-4b118ecb4c4b?w=1600&q=80",
    soundType: "orchestra",
    tags: ["Adventure", "Open World", "Puzzle"],
    owned: false,
    platforms: ["Switch"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "halo",
    title: "Halo Infinite",
    developer: "343 Industries",
    publisher: "Xbox Game Studios",
    genre: "First-Person Shooter",
    rating: 4.5,
    releaseDate: "2021-12-08",
    description: "When all hope is lost and humanity's fate hangs in the balance, the Master Chief steps forward to confront a terrifying new enemy. The most ambitious Halo campaign ever made.",
    coverUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b1b3c?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1600&q=80",
    soundType: "synth",
    tags: ["Sci-Fi", "Shooter", "Multiplayer"],
    owned: false,
    platforms: ["PC", "Xbox Series X|S", "Xbox One"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "ff7rebirth",
    title: "Final Fantasy VII Rebirth",
    developer: "Square Enix",
    publisher: "Square Enix",
    genre: "JRPG",
    rating: 4.8,
    releaseDate: "2024-02-29",
    description: "Step into a vibrant and vast world as Cloud and his friends seek to defy destiny itself. The second chapter of the FINAL FANTASY VII remake project blends classic RPG storytelling with action combat.",
    coverUrl: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=1600&q=80",
    soundType: "orchestra",
    tags: ["RPG", "Fantasy", "Action"],
    owned: false,
    platforms: ["PS5"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "starfield",
    title: "Starfield",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    genre: "Action RPG",
    rating: 4.3,
    releaseDate: "2023-09-06",
    description: "Explore the vast reaches of space in Bethesda's first new universe in over 25 years. Create your character and embark on an epic journey to uncover humanity's greatest mystery.",
    coverUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=1600&q=80",
    soundType: "synth",
    tags: ["Space", "Open World", "Sci-Fi"],
    owned: false,
    platforms: ["PC", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "horizon",
    title: "Horizon Forbidden West",
    developer: "Guerrilla Games",
    publisher: "Sony Interactive Entertainment",
    genre: "Action RPG",
    rating: 4.7,
    releaseDate: "2022-02-18",
    description: "Aloy ventures west to investigate a deadly blight that threatens all life on Earth. Explore stunning landscapes, battle colossal machines, and uncover a hidden threat.",
    coverUrl: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c1?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?w=1600&q=80",
    soundType: "orchestra",
    tags: ["Open World", "Sci-Fi", "Action"],
    owned: false,
    platforms: ["PS4", "PS5", "PC"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "diablo4",
    title: "Diablo IV",
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    genre: "Action RPG",
    rating: 4.4,
    releaseDate: "2023-06-06",
    description: "Explore the shattered world of Sanctuary in the most ambitious Diablo entry yet. Battle the legions of Hell through a dark and gripping campaign, then dive into deep endgame content.",
    coverUrl: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=1600&q=80",
    soundType: "ambient",
    tags: ["Dark Fantasy", "Multiplayer", "RPG"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "starwars",
    title: "Star Wars Jedi: Survivor",
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    genre: "Action Adventure",
    rating: 4.6,
    releaseDate: "2023-04-28",
    description: "Continue Cal Kestis's journey across the galaxy, now a more powerful Jedi. Master new combat abilities and explore a galaxy far, far away in this thrilling action-adventure.",
    coverUrl: "https://images.unsplash.com/photo-1543536448-d209d2d2e7d3?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&q=80",
    soundType: "orchestra",
    tags: ["Sci-Fi", "Action", "Adventure"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "liesofp",
    title: "Lies of P",
    developer: "Neowiz Games",
    publisher: "Neowiz",
    genre: "Souls-like",
    rating: 4.6,
    releaseDate: "2023-09-19",
    description: "A dark fantasy retelling of Pinocchio. Navigate a ruined city in a desperate search for Geppetto. Master a sophisticated combat system and wield a unique weapon customization system.",
    coverUrl: "https://images.unsplash.com/photo-1550639525-c97d455acf70?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=80",
    soundType: "orchestra",
    tags: ["Souls-like", "Dark Fantasy", "Action"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  },
  {
    id: "cyberpunk2077phantom",
    title: "Cyberpunk 2077: Phantom Liberty",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    genre: "Action RPG",
    rating: 4.9,
    releaseDate: "2023-09-26",
    description: "A spy-thriller expansion for Cyberpunk 2077. When a prototype orbital shuttle crash-lands in Dogtown, V is pulled into a dangerous game of espionage and survival featuring Idris Elba.",
    coverUrl: "https://images.unsplash.com/photo-1569144157591-c60f3f82f137?w=500&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&q=80",
    soundType: "synth",
    tags: ["Open World", "Spy Thriller", "Expansion"],
    owned: false,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    steamAppId: null,
    logoUrl: null,
    iconUrl: null,
    artworkFetched: false
  }
];
